### ISSUE TITLE
Can this work with Hassio ?

### ISSUE THREAD

**Issue by degreecy** [rianoc/tides#1]
This looks amazing and would love to have it implemented on my instance of HomeAssistant.  However, would or could this work with Hassio (i.e. the self contained OS + Home Assistant Core) ?  I don't think its possible to install "pip" ?

**Comment by rianoc** [comment]
I had this working successfully on HassIO.
My method is probably not how I should have done it but by pip installing to a specific folder which is persisted then everything worked. There's a section in the README.md

https://github.com/rianoc/tides#hassio-specifics
